version: "3"
services:
  redis:
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data:/data"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: freespaced
  web:
    image: freespace
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]