# auth API

###
# baseURL
@baseURL = http://localhost:3000
# @baseURL = https://freespace-api.herokuapp.com

###
# authToken
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmYTBjMzFmLWQ2NDItNDFlNC1iZjU2LWY0NGUyNDZiYmJmYSIsImlhdCI6MTYwNTQ2NzE2NiwiZXhwIjo0MTk3NDY3MTY2fQ.EUrV54sJhRSaMPVM3sPVp22T_M1FxuZm-r5KgVJoa-E
###
# signup
POST {{baseURL}}/signup
Content-Type: application/json

{
    "email": "testing123@gmail.com",
    "password": "12345678",
    "userId": "afa0c31f-d642-41e4-bf56-f44e246bbbfa"
}

 

###
# Login
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "testing123@gmail.com",
    "password": "12345678"
}

###
# me
GET   {{baseURL}}/me
Content-Type: application/json
x-auth-token: {{authToken}}

###
# forgotpassword
POST  {{baseURL}}/forgotpassword
Content-Type: application/json

{
    "email": "example@gmail.com"
}