# auth API

###
# baseURL
@baseURL = http://localhost:4000
# @baseURL = https://freespace-api.herokuapp.com

###
# authToken
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmYTBjMzFmLWQ2NDItNDFlNC1iZjU2LWY0NGUyNDZiYmJmYSIsImlhdCI6MTYwNTQ2NzE2NiwiZXhwIjo0MTk3NDY3MTY2fQ.EUrV54sJhRSaMPVM3sPVp22T_M1FxuZm-r5KgVJoa-E
###
# signup
POST {{baseURL}}/signup
Content-Type: application/json

{
    "email": "akuagwupadhilemon11@gmail.com",
    "password": "12345678"
}

    # "userId": "6d953481-9359-4875-a231-081bfd0766eb"
 

###
# Login
POST {{baseURL}}/login
Content-Type: application/json


{
    "email": "akuagwuphilemon11@gmail.com",
    "password": "12345678"
}

# {
#     "email": "akuagwuphilemon2019@gmail.com",
#     "password": "12345678"
# }

###

POST  https://freespace-api.herokuapp.com/therapist/signup
Content-Type: application/json

{
    "email": "newtherapist@freespaace.com", 
    "password":"therapist123"
    
}

###
POST  {{baseURL}}/therapist/waitlist
Content-Type: application/json

{
    "email":"sometext@gmail.com"
    
}

###
# me
GET   {{baseURL}}/me
Content-Type: application/json
x-auth-token: {{authToken}}

###
# forgotpassword
POST  {{baseURL}}/forgotpassword
Content-Type: application/json

{
    "email": "example@gmail.com"
}