#bookmark API

###
# authToken
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiNjAzZWJhLTEzOGQtNDA0ZC1hMjljLTdjZmQ3NjZhZDM3YSIsImlhdCI6MTYwNTM1NjYxMiwiZXhwIjo0MTk3MzU2NjEyfQ.2z0kyGqOXumISWAdCeMc2lAFXQXrlQ791EjJspgzsk0


###
# baseURL
@baseURL = http://localhost:3000

###
# Create Bookmark
 
POST {{baseURL}}/bookmark/create
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "storyId":"a1e353cd-bd9e-45b0-8ce6-3d54995e38c2"
}
###

GET {{baseURL}}/bookmark
Content-Type: application/json
x-auth-token: {{authToken}}

###
DELETE {{baseURL}}/bookmark/b5d45437-4a0e-4d32-b461-1488ff7e82dd
Content-Type: application/json
x-auth-token: {{authToken}}
