#bookmark API

###
# authToken
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiNjAzZWJhLTEzOGQtNDA0ZC1hMjljLTdjZmQ3NjZhZDM3YSIsImlhdCI6MTYwNDI2OTM3NCwiZXhwIjoxNjA0NTI4NTc0fQ.-8Qr8JIW87M2hN4PuCz2bCxAoD4t5XOmQ2rNZG8SdP0

###
# baseURL
@baseURL = http://localhost:3000

###
# Create Bookmark
 
POST {{baseURL}}/bookmark/create
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "storyId":"a1e353cd-bd9e-45b0-8ce6-3d54995e38c2"
}
###

GET {{baseURL}}/bookmark
Content-Type: application/json
x-auth-token: {{authToken}}