# comment API

###
# baseURL
@baseURL = http://localhost:3000

###
# authToken

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkYTE5NzU5LThmNWEtNDJmOC05NDgxLTExODM4YmU1MGE4YiIsImlhdCI6MTYwNDI1NjgxOSwiZXhwIjoxNjA0NTE2MDE5fQ.KSGsqw93uCgfO5rUbbKbcIJ7WJNv6h6Bo689w0YNG-A
@storyId = 1881cf31-b84f-45ff-b05e-6706b6f9e4ef

###

POST {{baseURL}}/comment/create 
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "storyId":"1881cf31-b84f-45ff-b05e-6706b6f9e4ef", 
 "content":"somethigl"
}

###
POST {{baseURL}}/comment/reply
Content-Type: application/json
x-auth-token:{{authToken}}

{
    "commentId":"e68eb4dc-2b33-4192-a07e-2ccad97db65e", 
    "content":"I like what I am seeing",
    "thugnssds":"afiodfd"
}