# comment API

###
# baseURL
@baseURL = http://localhost:4000

###
# authToken

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiNjAzZWJhLTEzOGQtNDA0ZC1hMjljLTdjZmQ3NjZhZDM3YSIsImlhdCI6MTYwNTM1NjYxMiwiZXhwIjo0MTk3MzU2NjEyfQ.2z0kyGqOXumISWAdCeMc2lAFXQXrlQ791EjJspgzsk0

@storyId = 1881cf31-b84f-45ff-b05e-6706b6f9e4ef

###

POST {{baseURL}}/comment/create 
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmNWRkZWFiLTk2NTEtNGQ3NS1iODQyLTUwNjc3OTBlZmRhZCIsImlhdCI6MTYwNzM4NjM0NSwiZXhwIjo0MTk5Mzg2MzQ1fQ.dL9GEA5AQQweSEVO3_M52_Rqlcfx0TR51ZznbuMYaO4

{
 
    "storyId":"47c569b6-2296-424f-9782-3d55060d2c0f",                                                                                                                                                                                                                                                                                       
    "content":"somethigadjaldfdlsomethigadjaldfdlsomethigadjaldfdlsomethigadjaldfdlsomethigadjaldfdlsomethigadjaldfdlsomethigadjaldfdl"
}

###
POST {{baseURL}}/comment/reply
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3NTM2ZGU1LWU1MGEtNDRmOC1iZjMxLThkMjdjY2QzMDQzYiIsImlhdCI6MTYwNzEzMjkzMiwiZXhwIjo0MTk5MTMyOTMyfQ.9nFBaTJEmoDtGF8wZRFOQa1QUpzG_0w-gE2aoAFE_Po

{
    "commentId":"d758bcb2-a58b-421e-bdc3-bf5a9585f188", 
    "content":"I like what I am seeing",
    "thugnssds":"afiodfd"
}