# Story API

###
# baseURL
@baseURL = http://localhost:3000
# @baseURL = https://freespace-api.herokuapp.com

###
# authToken
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiNjAzZWJhLTEzOGQtNDA0ZC1hMjljLTdjZmQ3NjZhZDM3YSIsImlhdCI6MTYwNDI2OTM3NCwiZXhwIjoxNjA0NTI4NTc0fQ.-8Qr8JIW87M2hN4PuCz2bCxAoD4t5XOmQ2rNZG8SdP0
###
@storyId = be6212a8-d99f-485a-8e23-7dbf3ac60ad3
# a1e353cd-bd9e-45b0-8ce6-3d54995e38c2

###
# GET ALL 
GET {{baseURL}}/story

###
# GET BY ID
GET {{baseURL}}/story/something-1048
Content-Type: application/json

###
# GET COMMENTS BY Story Id
GET {{baseURL}}/story/comments/{{storyId}}
Content-Type: application/json
###
#

GET {{baseURL}}/story/popular/getstories
###
# Create a story
POST {{baseURL}}/story/create
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "title":"something", 
    "text":"they are saying that this must be a string", 
    "allow_therapist":true, 
    "tags":[]
}

###
# create story as a loged in user 

POST {{baseURL}}/story/create
Content-Type: application/json

{
    "text":"they are saying that this must be a string", 
    "allow_therapist":true, 
    "tags":["fight", "war"],
    "creatorId": "fda19759-8f5a-42f8-9481-11838be50a8b"
 
}

###
PATCH {{baseURL}}/story/update  
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "title":"something more than gold", 
    "text":"adfvonolkadflk adfadfkadlf vadfk dfv adflkvd afvaf", 
    "allow_therapist": true, 
    "tags":["somethingnew", "anotherthing"],
    "id": "1156876b-665c-4863-bd07-b1b865a3e648"
}
###
DELETE  {{baseURL}}/story/delete/a5e6ca55-ba64-40ca-8d39-ee056523fb3c
Content-Type: application/json
x-auth-token: {{authToken}}
