# Story API

###
# baseURL
@baseURL = http://localhost:3000
# @baseURL = https://freespace-api.herokuapp.com

###
# authToken
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkYTE5NzU5LThmNWEtNDJmOC05NDgxLTExODM4YmU1MGE4YiIsImlhdCI6MTYwNDcxNDMzNywiZXhwIjoxNjA5MDM0MzM3fQ.nBg40GUNF7k9x6rtzaModUEH7t-ZZccMMnuzG4QVQNY
###
@storyId = be6212a8-d99f-485a-8e23-7dbf3ac60ad3
# a1e353cd-bd9e-45b0-8ce6-3d54995e38c2

###
# GET ALL 
GET {{baseURL}}/story?limit=4

###
# GET BY ID
GET {{baseURL}}/story/1863b961-077e-407e-a500-6623e2b3ea29
Content-Type: application/json

###

GET  {{baseURL}}/story/filter/sortstories?limit=3&sort=lastest

###
# GET COMMENTS BY Story Id
GET {{baseURL}}/story/comments/{{storyId}}
Content-Type: application/json
###
#

GET {{baseURL}}/story/popular/getstories?tag=war
###
# Create a story
POST {{baseURL}}/story/create
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "title":"something", 
    "text":"they are saying that this must be a string", 
    "allow_therapist":true, 
    "tags":[]
}
###
# a2c73854-8137-4420-b8bc-222a8354ed4b
# create story as a loged in user 

POST {{baseURL}}/story/create
Content-Type: application/json

{
    "text":"they are saying that this must be a string", 
    "allow_therapist":true, 
     "creatorId": "ee4d44a5-e76b-4135-87e0-ad780fa50f91",
    "tags":["fight", "war"],
    "title":"something" 
}

###
PATCH {{baseURL}}/story/update  
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "title":"something more than gold", 
    "text":"adfvonolkadflk adfadfkadlf vadfk dfv adflkvd afvaf", 
    "allow_therapist": true, 
    "tags":["somethingnew", "anotherthing"],
    "id": "1156876b-665c-4863-bd07-b1b865a3e648"
}
###
DELETE  {{baseURL}}/story/delete/a5e6ca55-ba64-40ca-8d39-ee056523fb3c
Content-Type: application/json
x-auth-token: {{authToken}}
###

PUT  {{baseURL}}/story/publish
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "storyId":"100d01b9-fc1f-4cea-8e1f-319689dd15e7",
    "publish":true
}