#bookmark API

###
#baseURL
@baseURL = http://localhost:3000


GET {{baseURL}}/tag
###

GET  {{baseURL}}/tag/name/war?limit=4
###
GET {{baseURL}}/tag/relatedstories/be6212a8-d99f-485a-8e23-7dbf3ac60ad3
###
GET {{baseURL}}/tag/trending