# users API

###
# baseURL
@baseURL = http://localhost:4000

###
 
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNkNDVhZGM5LTJhMWYtNDE5ZC1iZGM0LTNmODY0YzBmNzU1YyIsImlhdCI6MTYwNjkzMjg0OSwiZXhwIjo0MTk4OTMyODQ5fQ.wrF8GOHVfRbDoCgRPiDJmipciU22ba13VaPRcx7tyMc



###
# Get unauth user by id 
GET {{baseURL}}/users/story/6d953481-9359-4875-a231-081bfd0766eb


###
GET {{baseURL}}/users/story HTTP/1.1
Content-Type: application/json
x-auth-token: {{authToken}}
###
###
GET {{baseURL}}/users/notifications HTTP/1.1
Content-Type: application/json
x-auth-token: {{authToken}}
###

PUT {{baseURL}}/users/notification
Content-Type:  application/json
x-auth-token: {{authToken}}

{
    "notificationId":"12a8f742-c352-45ad-b420-c4383654987a"
}
###

PUT  {{baseURL}}/users/changepassword HTTP/1.1
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "oldPassword":"something", 
    "newPassword":"q1w2e3r4"
}

###
#change user email
PUT  {{baseURL}}/users/changeemail HTTP/1.1
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "email":"somethingelsde@gmail.com" 
}

###
PUT {{baseURL}}/users/updateprofile
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "firstname":"anewUser", 
    "lastname":"theuserlastname", 
    "username":"needstobe",
    "another":"sofa", 
    "profileimage": "http://localhost:3000/images/six.png",
    "coverimage": "https://images.pexels.com/photos/261055/pexels-photo-261055.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"

}

###
# Edit User By Id
PUT {{baseURL}}/users/1
Content-Type: application/json

{
    "email": "example@gmail.com",
	"password": "qwer1234"
}

###
# Del User By Id
DELETE {{baseURL}}/users/1

POST {{baseURL}}/posts
Content-Type: application/json

{
    "abc":"xyz",
    "foo":"bar"
}

#######
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json
x-auth-token: stsfgsfgg

{
    "abc":"xyz",
    "foo":"bar"
}

###
DELETE {{baseURL}}/users/
Content-Type: application/json
x-auth-token: {{authToken}}
