# users API

###
# baseURL
@baseURL = http://localhost:3000

###
# @authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkYTE5NzU5LThmNWEtNDJmOC05NDgxLTExODM4YmU1MGE4YiIsImlhdCI6MTYwNDI1NjgxOSwiZXhwIjoxNjA0NTE2MDE5fQ.KSGsqw93uCgfO5rUbbKbcIJ7WJNv6h6Bo689w0YNG-A
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkYTE5NzU5LThmNWEtNDJmOC05NDgxLTExODM4YmU1MGE4YiIsImlhdCI6MTYwNDUyNjM5MCwiZXhwIjoxNjA4ODQ2MzkwfQ.fEkxEtVdhW_WnqGRqoUNz1SkDn5yq5Axva13T7JTJbI

###
# Find All Users
GET {{baseURL}}/users

###
# Find User By Id
GET {{baseURL}}/users/1


###
# Add User
POST {{baseURL}}/users
Content-Type: application/json

{
    "email": "example@gmail.com",
	"password": "qwer1234"
}

###
# Get unauth user by id 
GET {{baseURL}}/users/story/1b603eba-138d-404d-a29c-7cfd766ad37a


###
GET {{baseURL}}/users/story HTTP/1.1
Content-Type: application/json
x-auth-token: {{authToken}}
###



PUT  {{baseURL}}/users/changepassword HTTP/1.1
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "oldPassword":"something", 
    "newPassword":"q1w2e3r4"
}
###
# Edit User By Id
PUT {{baseURL}}/users/1
Content-Type: application/json

{
    "email": "example@gmail.com",
	"password": "qwer1234"
}

###
# Del User By Id
DELETE {{baseURL}}/users/1

POST {{baseURL}}/posts
Content-Type: application/json

{
    "abc":"xyz",
    "foo":"bar"
}

#######
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json
x-auth-token: stsfgsfgg

{
    "abc":"xyz",
    "foo":"bar"
}